/// Flutter icons CustomAppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomAppIcons
///      fonts:
///       - asset: fonts/CustomAppIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomAppIcons {
  CustomAppIcons._();

  static const _kFontFam = 'CustomAppIcons';

  static const IconData traffic_cone = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData attention = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData attention_circled = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData truck = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData tags = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData glass = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData briefcase = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData bookmark_empty = const IconData(0xf097, fontFamily: _kFontFam);
  static const IconData download_cloud = const IconData(0xf0ed, fontFamily: _kFontFam);
  static const IconData upload_cloud = const IconData(0xf0ee, fontFamily: _kFontFam);
  static const IconData building = const IconData(0xf0f7, fontFamily: _kFontFam);
  static const IconData hospital = const IconData(0xf0f8, fontFamily: _kFontFam);
  static const IconData h_sigh = const IconData(0xf0fd, fontFamily: _kFontFam);
  static const IconData flag_empty = const IconData(0xf11d, fontFamily: _kFontFam);
  static const IconData flag_checkered = const IconData(0xf11e, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData plus_squared_alt = const IconData(0xf196, fontFamily: _kFontFam);
  static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam);
  static const IconData building_filled = const IconData(0xf1ad, fontFamily: _kFontFam);
  static const IconData cab = const IconData(0xf1b9, fontFamily: _kFontFam);
  static const IconData taxi = const IconData(0xf1ba, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xf206, fontFamily: _kFontFam);
  static const IconData bus = const IconData(0xf207, fontFamily: _kFontFam);
  static const IconData ship = const IconData(0xf21a, fontFamily: _kFontFam);
  static const IconData motorcycle = const IconData(0xf21c, fontFamily: _kFontFam);
  static const IconData train = const IconData(0xf238, fontFamily: _kFontFam);
  static const IconData subway = const IconData(0xf239, fontFamily: _kFontFam);
  static const IconData hourglass_1 = const IconData(0xf251, fontFamily: _kFontFam);
  static const IconData hourglass_2 = const IconData(0xf252, fontFamily: _kFontFam);
  static const IconData hourglass_3 = const IconData(0xf253, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xf254, fontFamily: _kFontFam);
  static const IconData font_awesome = const IconData(0xf2b4, fontFamily: _kFontFam);
}
